version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Docker/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Heladeria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
