# Usar la imagen oficial de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar la base de datos
ENV POSTGRES_DB Heladeria
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 12345

# Exponer el puerto de PostgreSQL
EXPOSE 5432
